#cloud-config
locale: es_ES.UTF-8
keyboard:
  layout: es
  variant: ''
timezone: Europe/Madrid


# Escribe la configuración de teclado persistente
write_files:

  - path: /etc/apt/apt.conf.d/99force-ipv4
    permissions: "0644"
    content: |
      Acquire::ForceIPv4 "true";
  - path: /etc/default/keyboard
    owner: root:root
    permissions: "0644"
    content: |
      XKBMODEL="pc105"
      XKBLAYOUT="es"
      XKBVARIANT=""
      XKBOPTIONS=""
      BACKSPACE="guess"



# Aplica el layout en esta sesión de consola (si existe) y ajusta locale
runcmd:
  - for i in {1..15}; do ping -c1 8.8.8.8 && break || sleep 2; done
  - for i in {1..10}; do getent hosts deb.debian.org && break || sleep 2; done
  - DEBIAN_FRONTEND=noninteractive apt-get update -o Acquire::ForceIPv4=true || true
  - DEBIAN_FRONTEND=noninteractive apt-get install -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" kbd || true
  - loadkeys es || true
  - 'command -v setupcon >/dev/null 2>&1 && setupcon || true'
  - localectl set-locale LANG=es_ES.UTF-8 || true
