network:
  version: 2
  ethernets:
    ens3:
      dhcp4: true
    ens4: 
      dhcp4: false
      addresses: ["192.168.201.1/24"]
    ens5: 
      dhcp4: false
      addresses: ["10.0.0.1/24"]

      