#cloud-config
hostname: backend
users:
  - name: debian
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHiYl8Co8WopWUl0IpwkIaGSJvJ5E18jojHVrxQQrGK/ sjnezsrez@gmail.com
chpasswd:
  expire: False
  users:
    - name: debian
      password: asdasd
      type: text
runcmd:
  - apt update
  - apt install -y apache2
  - cp /tmp/ficheros/index.html /var/www/html/
  - cp /tmp/ficheros/img.jpg /var/www/html/
  - cp /tmp/ficheros/htaccess /var/www/html/.htaccess
  - cp -r /tmp/ficheros/carpeta /var/www/html/
  - cp -r /tmp/ficheros/nuevodirectorio /var/www/html/
  - cp /tmp/ficheros/apache2.conf /etc/apache2/apache2.conf
  - chown -R www-data:www-data /var/www/html/
  - systemctl restart apache2