#cloud-config
hostname: server2
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users, admin
    shell: /bin/bash
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHiYl8Co8WopWUl0IpwkIaGSJvJ5E18jojHVrxQQrGK/ sjnezsrez@gmail.com
chpasswd:
  expire: False
  users:
    - name: ubuntu
      password: asdasd
      type: text

