#cloud-config
locale: es_ES.UTF-8
keyboard:
  layout: es
  variant: ''
timezone: Europe/Madrid

bootcmd:
  - for i in {1..15}; do ping -c1 8.8.8.8 && break || sleep 2; done
  - for i in {1..10}; do getent hosts deb.debian.org && break || sleep 2; done

# Escribe la configuración de teclado persistente
write_files:

  - path: /etc/apt/apt.conf.d/99force-ipv4
    permissions: "0644"
    content: |
      Acquire::ForceIPv4 "true";
  - path: /etc/default/keyboard
    owner: root:root
    permissions: "0644"
    content: |
      XKBMODEL="pc105"
      XKBLAYOUT="es"
      XKBVARIANT=""
      XKBOPTIONS=""
      BACKSPACE="guess"

# Instala utilidades de teclado (loadkeys). Si no hay red, simplemente seguirá.
package_update: true
packages:
  - kbd 
  - console-data


# Aplica el layout en esta sesión de consola (si existe) y ajusta locale
runcmd:
  - loadkeys es || true
  - 'command -v setupcon >/dev/null 2>&1 && setupcon || true'
  - localectl set-locale LANG=es_ES.UTF-8 || true
